// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICoreEx.Data;

namespace WebAPICoreEx.Migrations
{
    [DbContext(typeof(CustDbContext))]
    partial class CustDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPICoreEx.Models.Customer", b =>
                {
                    b.Property<string>("CId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<double>("CODLimit")
                        .HasColumnType("float");

                    b.HasKey("CId");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
